# Change these first
owner: chatainsim # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Yach
    url: https://yachman.duckdns.org
    icon: https://yachman.duckdns.org/static/icons/favicon.ico
  - name: Domo Easter
    url: https://domo.easter.fr
  - name: Gite du Galli
    url: https://gite-du-galli.fr
  - name: Box
    url: https://box.easter.fr

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
